### ISSUE TITLE
Resolve error

### ISSUE THREAD

**Issue by aandroide** [aandroide/myaddon#2]
@Mahmoudbakar2002 hi, you solved the crash, but it no longer updates automatically when I open Kodi and make a commit on github

**Comment by Mahmoudbakar2002** [comment]
Requirement was update when click check for update button

**Comment by aandroide** [comment]
not exactly, the requirement was to add that manual function but without eliminating the other automatic one.

**Comment by Mahmoudbakar2002** [comment]
Automatic one cause error because isn't sutiable for you project , that mean this service need to some updates to work fine .

And I didn't touched it , manual update is new feature with new code work separately from old code.

**Comment by Mahmoudbakar2002** [comment]
Automatic one cause error because isn't sutiable for you project , that mean this service need to some updates to work fine .

And I didn't touched it , manual update is new feature with new code work separately from old code.
