### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by aandroide** [aandroide/myaddon#4]
@Mahmoudbakar2002 
Hi, how can I hire you directly to complete 2 jobs? the freelancer no longer responds after paying him.

**Comment by Mahmoudbakar2002** [comment]
Call me in linked-in or Twitter, you can find them in my profile or send an email to [mahmoudatef.coder@gmail.com]

**Comment by aandroide** [comment]
@Mahmoudbakar2002 
https://github.com/aandroide/installer/blob/master/lo-scienziato-pazzo-installer/install_dependency.py
hi there is a small problem that occurs when installing a kubuntu image which is a derivative of ubuntu, practically when the script for installing the dependencies starts, it asks me for the sudo password but then the words "unable to download dependencies" appear but the strange thing is that if I restart Kodi, it asks me to enable iptvclient so in reality the installation of the dependencies has been performed but the installation success screen does not appear.
It seems like an error is caused in this part of code:
https://github.com/aandroide/installer/blob/934f3479d4ca9e09bb6e827ede6b22f08dea35ac/lo-scienziato-pazzo-installer/install_dependency.py#L133
can you please check?
A thousand thanks

**Comment by Mahmoudbakar2002** [comment]
Ok that will take 2 days and will cost 6 hours of work

**Comment by aandroide** [comment]
> Ok that will take 2 days and will cost 6 hours of work

price of an hour?

**Comment by Mahmoudbakar2002** [comment]
$50/hr

**Comment by Mahmoudbakar2002** [comment]
> > Ok that will take 2 days and will cost 6 hours of work
> 
> price of an hour?

$50/hr

**Comment by aandroide** [comment]
I'm sorry but it's too much! thank you all the same
